export const PODCAST_LIST_LOADING = 'PODCAST_LIST_LOADING'
export const PODCAST_LIST_SUCCESS= 'PODCAST_LIST_LOADING'
export const PODCAST_LIST_= 'PODCAST_LIST_LOADING'
export const PODCAST_LIST_LOADING = 'PODCAST_LIST_LOADING'